name: pr-safe-chain

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    if: |
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'github_actions')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Safe Chain
        run: |
          curl -fsSL https://raw.githubusercontent.com/AikidoSec/safe-chain/main/install-scripts/install-safe-chain.sh \
          | sh -s -- --ci

      - name: Install dependencies
        run: npm ci
